name: deploy PR previews

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - closed

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-preview-book:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v5

    # Install dependencies
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: esm-ws-24-25
        channel-priority: strict

    - name: Cache Conda env
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}', env.env_file)) }}
      id: cache-env

    - name: Update environment
      run: |
        conda env update -n esm-ws-24-25 -f environment.yaml
        echo "Run conda list" && conda list

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build data-science-for-esm

    # Deploy the preview
    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: data-science-for-esm/_build/html
